### ISSUE TITLE
[Question] What changes between using this library or leaving the OS manage TabTip.exe?

### ISSUE THREAD

**Issue by FrancescoBonizzi** [Seuleuzeuh/WPFTabTipMixedhardware#2]
With the latest Windows builds, if your PC has a touch screen and there is no hardware keyboard connected, Windows automatically spawns the TabTip.exe virtual keyboard. I believe it starts the process when Windows starts.

However I noticed that sometimes the textbox doesn't raises anymore the virtual keyboard. (Or maybe TabTip.exe did crash, I couldn't verify that). 

So I'm wondering if this library could help with the issue or if with the new built-in integration it isn't necessary.

**Comment by Seuleuzeuh** [comment]
Hi Francesco,

I used this library in an app delivred to many OS version (7, 8.1, 10, Server 2008 to 2019), not only W10.
I first try to used the built-in OS Support in W10 but i've notice that is not fully work (like you, with simple TextBox, sometimes the virtual keyboard doesn't show, sometimes it was displayed but auto close one second later). I've try to looking for why is not working well in the app but i've not found how to make it work properly (i expected behavior close to automation - AutomationPeer -, but not found it). Especially with custom control or templated control - we use Telerik UI components with complex template and styling.

More over, the clients work with touchscreen along with Keyboard/Mouse and use one or other according to the view/facility of use. So, i've modified the initial repo to work properly with this behavior (with the possibility to chose when the TabTip must be displayed).

If you find a way to make it work properly with the OS built-in functionnality, i'm interested by the solution ! :wink:

**Comment by FrancescoBonizzi** [comment]
Thanks a lot for sharing your experience!

In my case I have a only touch machine and a "single page application" with WPF in which I navigate the pages within a Frame. I have no custom input controls, I use the basic TextBox. I noticed that sometimes when the TextBox gets focus (I see that the border color changes) the virtual keyboard does not show. Initially I was wondering about the TabTip.exe process that might be crashed, but after inspecting the OS I saw it running. I also noticed that If I enter in remote desktop in the machine and click inside the page the virtual keyboard begin working as expected.

My last hypothesis is that it is a problem of focus, so in the last build - since I didn't find a way to reproduce the issue when I want, did you? - I tried to set the main windows as `TopMost=true` and to register for the `Deactivated` event to call `Activate()`.

Let's see what will happen. If you have further considerations based on my experience, please share it 😁

**Comment by Seuleuzeuh** [comment]
It was a long time ago, but i don't think the focus was involved. I have one other application (only with touchscreen) opened in FullScreen so always on top and always focused, and i've see the same problem. I've not found any repro step to this issue...

**Comment by FrancescoBonizzi** [comment]
Thanks a lot! Let's what's happening!
